name: scenedino
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.10
  - pytorch==2.3.0
  - torchvision==0.18.0
  - pytorch-cuda=12.1
  - pydensecrf
  - pip
  - pip:
      - tensorflow-datasets
      - pytorch-ignite
      - hydra-core
      - omegaconf
      - lpips
      - dotmap
      - dotdict
      - pytorch-msssim
      - plyfile
      - tensorflow  # for tensorboard
      - opencv-python
      - matplotlib
      - numpy==1.26.4
      - scipy
      - scikit-image
      - timm
      - kornia
      - numba
      - pykeops
      - PuLP
      - optuna
      - gradio
      - open3d  # for gradio demo
